name: 'Install Dependencies'
description: 'Install Eigen, Boost and other dependencies required by vinecopulib'
inputs:
  os:
    description: 'The operating system to install dependencies for'
    required: false
    default: 'ubuntu-latest'
  platform:
    description: 'The platform to install dependencies for'
    required: false
    default: 'x64'
  boost:
    description: 'Whether to install Boost'
    required: false
    default: true
  boost_install_dir:
    description: 'The directory to install Boost to'
    required: false
    default: '/home/runner/work'
  boost_version:
    description: 'The version of Boost to install'
    required: false
    default: '1.84.0'
  eigen:
    description: 'Whether to install Eigen'
    required: false
    default: true
  eigen_install_dir:
    description: 'The directory to install Eigen to'
    required: false
    default: '/home/runner/work'
  eigen_version:
    description: 'The version of Eigen to install'
    required: false
    default: '3.4.0'
  lcov:
    description: 'Whether to install lcov'
    required: false
    default: true
  R:
    description: 'Whether to install R'
    required: false
    default: false
  update_compilers_ubuntu:
    description: 'Whether to update the compilers on Ubuntu'
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Update compilers on ubuntu
      if: ${{ inputs.update_compilers_ubuntu }} && ${{ inputs.os == 'ubuntu-latest' }}
      run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y g++ clang
          sudo apt-get autoremove
      shell: bash

    - name: Install boost ${{inputs.boost_version}}
      if: ${{ inputs.boost }}
      uses: MarkusJx/install-boost@v2.3.1
      with:
          boost_version: ${{inputs.boost_version}}
          boost_install_dir: ${{ inputs.boost_install_dir }}

    - name: Install Eigen ${{inputs.eigen_version}}
      if: ${{ inputs.eigen }}
      run: |
          git clone --depth 1 --branch ${{inputs.eigen_version}} https://gitlab.com/libeigen/eigen ${{inputs.eigen_install_dir}}/eigen
      shell: bash


    - name: Install lcov
      if: ${{ inputs.lcov }} && ${{ inputs.os == 'ubuntu-latest' }}
      run: |
          sudo apt-get install --no-install-recommends -y lcov
      shell: bash

    - name: Install R
      if: ${{ inputs.install_R }}
      uses: r-lib/actions/setup-r@v2
    - name: Install VineCopula
      if: ${{ inputs.install_R }}
      run: |
        if [ "${{ inputs.os }}" == "ubuntu-latest" ]; then
            sudo apt-get install --no-install-recommends -y libgsl0-dev
          elif [ "${{ inputs.os }}" == "macos-latest" ]; then
            brew install gsl
          elif [ "${{ inputs.os }}" == "windows-latest" ]; then
            cmd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ inputs.platform }}
            # choco upgrade cmake
            choco install wget
            wget https://github.com/vinecopulib/pyvinecopulib/raw/main/lib/boost_1_71_0.tar.gz
            set current_dir=%CD%
            echo %current_dir%  
            pwd
            echo "${Boost_INCLUDE_DIR}"
            tar xzvf boost_1_71_0.tar.gz
            # choco install boost-msvc-14.3
            choco install eigen
          fi
          Rscript -e "install.packages('VineCopula', repos='http://cran.rstudio.com/')"
      shell: bash