language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
 #   - os: osx
 #        sudo: required

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo sh -c 'echo "deb https://cloud.r-project.org/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi

install:
  ### LINUX
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libeigen3-dev libnlopt-dev libgsl0-dev gsl-bin; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install r-base r-base-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install doxygen doxygen-doc doxygen-gui graphviz; fi

  ### OSX
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew tap homebrew/science && brew install eigen gsl nlopt; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install cask && brew cask install xquartz && brew install r; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install doxygen; fi

  ### Common
  - sudo Rscript -e 'install.packages(c("Rcpp","RInside","RcppEigen","VineCopula"), repos="https://cloud.r-project.org/", type="source")'

script:
  - mkdir build
  - mkdir bin
  - cd build
  - cmake .. && make && make doc
  - cd ../bin
  - ./test_bicop_parametric

notifications:
  email:
    - thibault.vatter@gmail.com
