init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap #R
  - travis-tool.sh r_install RcppEigen RInside VineCopula

#TODO: after we get rid of the dependency on R
#  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.2.zip -OutFile eigen.zip
#  - 7z x eigen.zip -o"C:\projects" -y > nul

  - ps: wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2-dll64.zip -OutFile nlopt.zip
  - 7z x nlopt.zip -o"C:\projects\nlopt" -y > nul

before_build:
  - md build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\Libraries\boost_1_63_0 -DEIGEN3_INCLUDE_DIR="C:\Program Files\R\R-3.3.2patched\library\RcppEigen\include" -DCMAKE_INCLUDE_PATH="C:\projects\nlopt;C:\Program Files\R\R-3.3.2patched\library\Rcpp\include" -DCMAKE_LIBRARY_PATH="C:\projects\nlopt;c:\Program Files\R\R-3.3.2patched\library\Rcpp\libs"

build_script:
  - cmake --build .

test_script:
  - ctest --output-on-failure
