install:
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.2.zip -OutFile eigen.zip
  - 7z x eigen.zip -o"C:\projects" -y > nul

before_build:
  - md build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=C:\Libraries\boost_1_63_0 -DEIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-da9b4e14c255

build_script:
  - cmake --build .

test_script:
  - ctest --output-on-failure
